spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kea?useUnicode=true&characterEncdoing=UTF-8&serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create

  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10